In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [28]:
df=pd.read_csv("Churn_Modelling.csv")

In [29]:
df.head(5)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [30]:
df.drop(["RowNumber", "CustomerId", "Surname"], axis=1, inplace=True)

In [31]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [32]:
label_encoder=LabelEncoder()
df["Gender"]=label_encoder.fit_transform(df["Gender"])

In [33]:
onehotencoder=OneHotEncoder(sparse_output=False)
encoded=onehotencoder.fit_transform(df[["Geography"]])

In [34]:
encoded_df=pd.DataFrame(encoded,columns=onehotencoder.get_feature_names_out(["Geography"]))

In [35]:
df=df.drop("Geography",axis=1)
df=pd.concat([df,encoded_df],axis=1)

In [36]:
df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CreditScore        10000 non-null  int64
 1   Gender             10000 non-null  int32
 2   Age                10000 non-null  int64
 3   Tenure             10000 non-null  int64
 4   Balance            10000 non-null  float64
 5   NumOfProducts      10000 non-null  int64
 6   HasCrCard          10000 non-null  int64
 7   IsActiveMember     10000 non-null  int64
 8   EstimatedSalary    10000 non-null  float64
 9   Exited             10000 non-null  int64
 10  Geography_France   10000 non-null  float64
 11  Geography_Germany  10000 non-null  float64
 12  Geography_Spain    10000 non-null  float64
dtypes: float64(5), int32(1), int64(7)
memory usage: 976.7 KB

In [38]:
x=df.drop("EstimatedSalary",axis=1)
y=df["EstimatedSalary"]

In [40]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [44]:
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [47]:
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

with open('label_encoder.pkl','wb') as file:
    pickle.dump(label_encoder,file)

with open('onehotencoder.pkl','wb') as file:
    pickle.dump(onehotencoder,file)

***ANN Regression Problem***

In [48]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [49]:
model=Sequential([
    Dense(64, activation='relu', input_shape=(x_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1, activation='linear')
])

e:\alternative of C\anaconda\Lib\site-packages\keras\src\layers\core\dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [50]:
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mean_absolute_error'])

In [51]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [52]:
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [54]:
log_dir="regressionlogs/fit/"+datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [55]:
early_stopping_callback=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [56]:
history=model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=100,callbacks=[tensorboard_callback,early_stopping_callback])

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 101583.4609 - mean_absolute_error: 101583.4609 - val_loss: 98511.5312 - val_mean_absolute_error: 98511.5312
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 99922.5234 - mean_absolute_error: 99922.5234 - val_loss: 96932.7578 - val_mean_absolute_error: 96932.7578
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 97474.9141 - mean_absolute_error: 97474.9141 - val_loss: 92797.3906 - val_mean_absolute_error: 92797.3906
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 92251.3203 - mean_absolute_error: 92251.3203 - val_loss: 85904.4922 - val_mean_absolute_error: 85904.4922
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 86060.4375 - mean_absolute_error: 86060.4375 - val_loss: 77140.8906 - val_mean_absolute_error: 77140.8906
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 76705.4531 - mean_absolute_error: 76705.4531 - val_loss: 68127.7969 - val_mean_absolute_error: 68127.7969
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 67532.9531 - mean_absolute_error: 67532.9531 - val_loss: 60426.8203 - val_mean_absolute_error: 60426.8203
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 59783.6719 - mean_absolute_error: 59783.6719 - val_loss: 55164.3828 - val_mean_absolute_error: 55164.3828
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 54650.2461 - mean_absolute_error: 54650.2461 - val_loss: 52338.2969 - val_mean_absolute_error: 52338.2969
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 51631.1758 - mean_absolute_error: 51631.1758 - val_loss: 51110.4609 - val_mean_absolute_error: 51110.4609
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 50616.1289 - mean_absolute_error: 50616.1289 - val_loss: 50709.8281 - val_mean_absolute_error: 50709.8281
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 50147.9102 - mean_absolute_error: 50147.9102 - val_loss: 50587.8906 - val_mean_absolute_error: 50587.8906
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 50307.7695 - mean_absolute_error: 50307.7695 - val_loss: 50527.9492 - val_mean_absolute_error: 50527.9492
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 50263.9570 - mean_absolute_error: 50263.9570 - val_loss: 50489.1133 - val_mean_absolute_error: 50489.1133
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49945.3984 - mean_absolute_error: 49945.3984 - val_loss: 50446.0664 - val_mean_absolute_error: 50446.0664
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49830.4766 - mean_absolute_error: 49830.4766 - val_loss: 50404.8594 - val_mean_absolute_error: 50404.8594
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 50189.8633 - mean_absolute_error: 50189.8633 - val_loss: 50374.8359 - val_mean_absolute_error: 50374.8359
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 50189.2969 - mean_absolute_error: 50189.2969 - val_loss: 50347.1133 - val_mean_absolute_error: 50347.1133
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 50325.1523 - mean_absolute_error: 50325.1523 - val_loss: 50333.7734 - val_mean_absolute_error: 50333.7734
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 50111.6875 - mean_absolute_error: 50111.6875 - val_loss: 50305.4453 - val_mean_absolute_error: 50305.4453
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49680.0156 - mean_absolute_error: 49680.0156 - val_loss: 50295.5156 - val_mean_absolute_error: 50295.5156
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49620.7656 - mean_absolute_error: 49620.7656 - val_loss: 50288.3125 - val_mean_absolute_error: 50288.3125
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49235.4492 - mean_absolute_error: 49235.4492 - val_loss: 50275.7930 - val_mean_absolute_error: 50275.7930
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 50317.5078 - mean_absolute_error: 50317.5078 - val_loss: 50261.6992 - val_mean_absolute_error: 50261.6992
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49994.7109 - mean_absolute_error: 49994.7109 - val_loss: 50263.3008 - val_mean_absolute_error: 50263.3008
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 50281.6289 - mean_absolute_error: 50281.6289 - val_loss: 50247.7969 - val_mean_absolute_error: 50247.7969
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 50200.3164 - mean_absolute_error: 50200.3164 - val_loss: 50240.8438 - val_mean_absolute_error: 50240.8438
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49641.7969 - mean_absolute_error: 49641.7969 - val_loss: 50238.9453 - val_mean_absolute_error: 50238.9453
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 50016.5273 - mean_absolute_error: 50016.5273 - val_loss: 50235.1719 - val_mean_absolute_error: 50235.1719
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49708.2930 - mean_absolute_error: 49708.2930 - val_loss: 50240.8828 - val_mean_absolute_error: 50240.8828
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49298.7227 - mean_absolute_error: 49298.7227 - val_loss: 50237.2188 - val_mean_absolute_error: 50237.2188
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 48967.9805 - mean_absolute_error: 48967.9805 - val_loss: 50240.6016 - val_mean_absolute_error: 50240.6016
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49820.1016 - mean_absolute_error: 49820.1016 - val_loss: 50234.2695 - val_mean_absolute_error: 50234.2695
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 50415.7500 - mean_absolute_error: 50415.7500 - val_loss: 50238.3750 - val_mean_absolute_error: 50238.3750
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 50350.0859 - mean_absolute_error: 50350.0859 - val_loss: 50230.5742 - val_mean_absolute_error: 50230.5742
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49745.3203 - mean_absolute_error: 49745.3203 - val_loss: 50237.9570 - val_mean_absolute_error: 50237.9570
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49804.3438 - mean_absolute_error: 49804.3438 - val_loss: 50236.4062 - val_mean_absolute_error: 50236.4062
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49417.1992 - mean_absolute_error: 49417.1992 - val_loss: 50234.7383 - val_mean_absolute_error: 50234.7383
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49546.9922 - mean_absolute_error: 49546.9922 - val_loss: 50238.2773 - val_mean_absolute_error: 50238.2773
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49390.0898 - mean_absolute_error: 49390.0898 - val_loss: 50246.6641 - val_mean_absolute_error: 50246.6641
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49809.2383 - mean_absolute_error: 49809.2383 - val_loss: 50243.0781 - val_mean_absolute_error: 50243.0781
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49943.7656 - mean_absolute_error: 49943.7656 - val_loss: 50244.1172 - val_mean_absolute_error: 50244.1172
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49434.8945 - mean_absolute_error: 49434.8945 - val_loss: 50246.8516 - val_mean_absolute_error: 50246.8516
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49790.7969 - mean_absolute_error: 49790.7969 - val_loss: 50248.5195 - val_mean_absolute_error: 50248.5195
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49155.6719 - mean_absolute_error: 49155.6719 - val_loss: 50240.8086 - val_mean_absolute_error: 50240.8086

In [58]:
%load_ext tensorboard

%tensorboard --logdir regressionlogs/fit

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

Reusing TensorBoard on port 6006 (pid 23744), started 0:01:09 ago. (Use '!kill 23744' to kill it.)

In [59]:
## Evalute model on test data
test_loss,test_mae=model.evaluate(x_test,y_test)
print(f"Test Loss: {test_loss}, Test MAE: {test_mae}")

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 51103.0469 - mean_absolute_error: 51103.0469
Test Loss: 50230.57421875, Test MAE: 50230.57421875

In [60]:
model.save("salary_regression_model.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.